theme: jekyll-theme-minimal
title: Alice Noakes
description: Alice Noakes is a product manager. She loves leading teams to design and build great digital services. 
Alice currently works at GDS, and previously in educational technology and publishing.
